version: '2'
services:
    rrm-app:
        image: rrm
        external_links:
            - rrm-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/rrm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rrm-postgresql:
        extends:
            file: postgresql.yml
            service: rrm-postgresql
