version: '2'
services:
    rrm-postgresql:
        container_name: rrm-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/rrm/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=rrm
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
